title: Tecnocriollo blog
description: A personal blog about various topics.
url: https://tecnocriollo.github.io
author: Patricio Sanchez
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag